Create docs-elastic-staging-publish.yml
elastic/workflows pull request #18
Opened 2023-03-29 22:05 UTC by scottybollinger

In pursuit of https://github.com/elastic/docsmobile/issues/378

I have a TODO to update the README to remove the project names and secrets from the template code after we remove the required attribute and hard-code the name in the workflows.

2023-03-29 22:06 UTC, scottybollinger commented on .github/workflows/docs-elastic-staging-publish.yml
> +          repository: elastic/${{ inputs.prebuild }}
This relies on an `input`. What are the ramifications for the migration to staging and then the promotion to docs.elastic.co?

2023-03-31 20:42 UTC, glitteringkatie requested changes
Two nits but this looks good!

2023-03-31 20:42 UTC, glitteringkatie commented on .github/workflows/docs-elastic-staging-publish.yml
> +      - name: Checkout dev doc docsmobile app
```suggestion
      - name: Checkout staging site repo
```

2023-03-31 20:42 UTC, glitteringkatie commented on README.md
> +For example, if you do not have a docs dir, use the correct dir or no dir instead.
```suggestion
```

We no longer default to having the docs dir in front of things so I don't think this is necessary

2023-03-31 23:32 UTC, glitteringkatie approved these changes
Yay!

2023-03-31 23:33 UTC, merged